### ISSUE TITLE
Goodix i2c touchscreen

### ISSUE THREAD

**Issue by goutx2** [lineage-rpi/android_kernel_brcm_rpi#11]
First of all thanks for this great work I have a rpi4 4 gb and 7 inche i2c goodix touchscreen 
For the official raspberry os i just add a line to config.txt file to make it work 
dtoverlay=goodix
And i2c=on 
But it not work on lenageos
I tried i2cdetect  -1 
And i can see 14 reg so the touchscreen work but how to load the driver
What i have to do to make it work

**Comment by KonstaT** [comment]
Can you provide a bit more detail about the touchscreen. Does it have HDMI interface for display and I2C is used for touch input?

Goodix touchscreen driver is not built into the kernel so that is why it's not loaded.
https://github.com/lineage-rpi/android_kernel_brcm_rpi/blob/lineage-17.1/arch/arm/configs/lineageos_rpi4_defconfig#L2273

You would need to recompile the kernel with that option enabled. There's build instructions for the kernel available here:
https://github.com/lineage-rpi/android_kernel_brcm_rpi/issues/10#issuecomment-739346981

You might need to create an IDC file for it on the Android side as well (https://source.android.com/devices/input/input-device-configuration-files & see e.g. /vendor/usr/idc/ADS7846_Touchscreen.idc in my builds for reference).

**Comment by goutx2** [comment]
Thank you for your reply. 
So it's two sperates
![FB_IMG_1610797644147](https://user-images.githubusercontent.com/60521162/104811183-335b6400-57fa-11eb-8af7-f062e7bd4259.jpg)
![FB_IMG_1610797682630](https://user-images.githubusercontent.com/60521162/104811189-3a827200-57fa-11eb-8b78-704cea414e61.jpg)

 parts i connect display to HDMI
And touchscreen to i2c interface its kind of homebrew work 
From what i understand i have to recompile the kernel than flash it via twrp ?

**Comment by KonstaT** [comment]
In that case I think you should be able to get this working.

When you compile the kernel you'll get zImage that you can simply copy to the boot partition to replace the original kernel (/boot/zImage).

Check 'dmesg' output on booting the device that the driver is loaded. You should also see it listed as input device (see /sys/class/input/input*).

**Comment by goutx2** [comment]
Thanks i will close the issue

**Comment by KonstaT** [comment]
Did you get this working? What steps did it require?

I could include the necessary changes in future builds to make it easier for the next person with goodix touchscreen.

**Comment by goutx2** [comment]
Not yet  i have to recompile the kernel as you said but to be honest i am not familiar with this staff
I will appreciate if you could make zimage for me and i will report if it will work

**Comment by goutx2** [comment]
> Can you provide a bit more detail about the touchscreen. Does it have HDMI interface for display and I2C is used for touch input?
> 
> Goodix touchscreen driver is not built into the kernel so that is why it's not loaded.
> https://github.com/lineage-rpi/android_kernel_brcm_rpi/blob/lineage-17.1/arch/arm/configs/lineageos_rpi4_defconfig#L2273
> 
> You would need to recompile the kernel with that option enabled. There's build instructions for the kernel available here:
> [#10 (comment)](https://github.com/lineage-rpi/android_kernel_brcm_rpi/issues/10#issuecomment-739346981)
> 
> You might need to create an IDC file for it on the Android side as well (https://source.android.com/devices/input/input-device-configuration-files & see e.g. /vendor/usr/idc/ADS7846_Touchscreen.idc in my builds for reference).

After a week finally i get zImage i recompiled the kernel with goodix touchscreen driver built in and this is the first step . just tell me how to add IDC fille for goodix from what i understand i have to rename ADS7846_Touchscreen.idc to goodix.idc is this right?

**Comment by goutx2** [comment]
Hi again i confirm it work perfectly without adding any IDC file 
Thes is my steps to make it work 
Modify
 https://github.com/lineage-rpi/android_kernel_brcm_rpi/blob/lineage-17.1/arch/arm/configs/lineageos_rpi4_defconfig#L2273 
CONFIG_TOUCHSCREEN_GOODIX=y
Then compile the kernel and copy paste zImage
Modify config.txt 
dtparam=i2c_arm=on
dtoverlay=goodix 
Wiring following the picture
And booom it work
![goodix-first_bb](https://user-images.githubusercontent.com/60521162/105610222-d9850c00-5dae-11eb-8d22-4aa965798ef5.png)

**Comment by KonstaT** [comment]
Cool, good to hear you got it figured out.

I'll enable the goodix touchscreen driver for future builds.
