### ISSUE TITLE
LineageOS 18.1 (android11-kernel5.4) build step

### ISSUE THREAD

**Issue by kernel-cyrus** [lineage-rpi/android_kernel_brcm_rpi#15]
Hi,

I'm building LineageOS 18.1 for raspi4b. I want to build the kernel standalone. Can you give the build steps?

Thank you
Cyrus

**Comment by KonstaT** [comment]
Exactly the same steps as in https://github.com/lineage-rpi/android_kernel_brcm_rpi/issues/10#issuecomment-739346981 but use lineage-18.1 branch instead of lineage-17.1.
