### ISSUE TITLE
Second screen

### ISSUE THREAD

**Issue by hackintoshlover** [lineage-rpi/android_kernel_brcm_rpi#18]
Hi,
I was trying to enable second screen but it seems to not work.
So I enable desktop mode and all related options in settings.
After which if I connect one display everything works fine but as soon as I connect other display,
The main display hangs and eventually both the screen go blank.
I thought might be a screen issue so tried different screens but still getting the same result.
Could you please tell what steps to follow to achieve the same?
The system definitely detects two displays.

**Comment by KonstaT** [comment]
There's no support for secondary displays.
