### ISSUE TITLE
Accesing GPIO from Android SDK?

### ISSUE THREAD

**Issue by DeLaiT** [lineage-rpi/android_kernel_brcm_rpi#19]
Is it possible to programatically access GPIO pins (in/out) on the Rpi 4B board while having this lineageOS installed?

**Comment by KonstaT** [comment]
Seems more of a question than issues with the Linux kernel.
https://konstakang.com/devices/rpi4/LineageOS18/
https://forums.raspberrypi.com/viewtopic.php?f=73&t=297349&sid=5e3de6ec1431d94faea4ca9ea5b8e608
https://forum.xda-developers.com/t/dev-rom-unofficial-lineageos-18-1-android-11-for-raspberry-pi-4-b.4212945/
are few places where things like this have already been discussed.

It depends what you want to do with the GPIO. Android doesn't have any built-in API for GPIO access. You can e.g. access the GPIO using sysfs (https://forums.raspberrypi.com/viewtopic.php?f=73&t=220613#p1404555).
