### ISSUE TITLE
arm64-v8a support?

### ISSUE THREAD

**Issue by GMatrixGames** [lineage-rpi/android_kernel_brcm_rpi#2]
Hello,

I've been looking for a LineageOS build that's arm64 for the raspberry pi 4b.
I was wondering if the latest release on your site is arm64, or is there a way to get it working under arm64 instead of armeabi-v7a

Thanks!

**Comment by KonstaT** [comment]
Latest build is arm. There's no current plans to switch to arm64 builds.
