### ISSUE TITLE
problemi di codice

### ISSUE THREAD

**Issue by adriano98bis** [lineage-rpi/android_kernel_brcm_rpi#23]
Buon giorno, ho seguito le istruzioni per compilare una nuova versione del kernel lineage os per raspberry pi dal mio portatile a cui ho aggiunto un unità di memoria usb con l'istallazione dell'ultima versione di ubuntu, ma digitando i codici specificati nelle istruzioni il terminale di ubunto non riesce a trovare i file richiesti ?

grazie per l'attenzione.

**Comment by KonstaT** [comment]
Koita englanniksi seuraavalla kerralla.
