### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ha-zhuzhu** [lineage-rpi/android_kernel_brcm_rpi#24]
Hi, I was trying to build lineage-19.0 for rpi4, 64-bit by following your instruction in another issue, but here's what I got:

```
DTC     arch/arm64/boot/dts/broadcom/bcm2837-rpi-3-a-plus.dtb
arch/arm64/boot/dts/broadcom/bcm2837-rpi-3-a-plus.dts:2:10: fatal error: arm/bcm2837-rpi-3-a-plus.dts: No such file or directory
    2 | #include "arm/bcm2837-rpi-3-a-plus.dts"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Could you help me with that? Thanks!

**Comment by KonstaT** [comment]
What steps did you follow? I haven't come across such issue.

There's already a discussion for compiling kernels here https://github.com/lineage-rpi/android_kernel_brcm_rpi/issues/10.
