### ISSUE TITLE
Full build but not get the zImage.img

### ISSUE THREAD

**Issue by ilike28** [lineage-rpi/android_kernel_brcm_rpi#25]
Dear Sirs

I used the command which is "mka -j4 kernel ramdisk systemimage vendorimage".
But It doesn't produce the boot image.
Could you please tell me how can make it @@?

Thanks ^_^

![image](https://user-images.githubusercontent.com/19503973/144750449-95e0e238-e4be-47b9-9f8c-5e380cd71489.png)

**Comment by KonstaT** [comment]
Kernel builds steps are available at https://github.com/lineage-rpi/android_kernel_brcm_rpi/issues/10#issuecomment-739346981.

The 'kernel' you've highlighted is a copy of the kernel zImage (32-bit) or Image (64-bit). Just rename the file (copy it as zImage/Image and replace the existing file on the boot partition of the Android image you're targeting). You can also find all the kernel build artifacts inside obj/KERNEL_OBJ/ directory on the out dir you're already at.

There's no boot image on the Pi like on regular Android devices. Boot partition is used instead.

**Comment by ilike28** [comment]
Thanjks ^_^
