### ISSUE TITLE
sensor bmp280 i2c driver in the lineage-18.1 doesn;t work

### ISSUE THREAD

**Issue by ilike28** [lineage-rpi/android_kernel_brcm_rpi#26]
I download the following image.
lineage-18.1-20211123-UNOFFICIAL-KonstaKANG-rpi4.zip
https://www.androidfilehost.com/?fid=7161016148664844942
md5:72e9236baa3cb5ae6e65af210ccae939

And I connected a BMP280 sensor by I2c pin. (3.3V/SDA/SDL/GND)
I2cDetect found that sensor's whoami is 0x77.  But not UU?
And the Sensor can not find by the android sensor app.

Could you please tell me where i did wrong??

Thanks ^_^

![image](https://user-images.githubusercontent.com/19503973/145075548-cc96ed02-5971-47f6-819c-19d3ef700f61.png)

![image](https://user-images.githubusercontent.com/19503973/145075329-a7241e6d-3801-4166-b46e-36009f20daa1.png)

**Comment by KonstaT** [comment]
BMP280 is expected to be at 0x76 (https://github.com/lineage-rpi/android_kernel_brcm_rpi/blob/lineage-18.1/arch/arm/boot/dts/overlays/android-i2c-sensor-overlay.dts#L95).

In this case enabling the sensor under Settings -> System -> Advanced settings -> Sensors is not enough and you need to modify /boot/config.txt manually (`dtoverlay=android-i2c-sensor,bmp280,addr=0x77`).
