### ISSUE TITLE
Cannot boot from compiled image

### ISSUE THREAD

**Issue by yizhepku** [lineage-rpi/android_kernel_brcm_rpi#27]
Following the build instructions in #10, I compiled the kernel as part of Android build on the lineage-17.1 branch. The compliation was sucessful, producing artifacts like `system.img` and `zImage` as expected. Then I created a flashable image using `mkimg.sh`. So far so good.

However, I noticed my image is quite different from [the prebuilt image](https://konstakang.com/devices/rpi4/LineageOS17.1/). For example, there's no `/boot` directory in `system.img`, so when I tried to boot the system, it complains that the boot partition cannot be mounted. Even after I manually create a `/boot` directory, the boot process fails with various errors. Here's a log of the booting process on [pastebin](https://pastebin.com/NRgEtyPe).

Did I mess up at some point? I would appreciate guidance on how to proceed.

**Comment by KonstaT** [comment]
There's source code and build instructions for my LineageOS 14.1 & 15.1 builds for Pi 3 (https://github.com/lineage-rpi/android_local_manifest/tree/cm-14.1 & https://github.com/lineage-rpi/android_local_manifest/tree/lineage-15.1, respectively). I haven't released full device specific configuration and manifest for my LineageOS 16.0, 17.1, 18.1 & 19.0 builds (both Pi 3 & Pi 4). You can build the Linux kernel (and other GPL licensed parts), graphics drivers/HALs, and various other HALs/components using the sources I've released.
