### ISSUE TITLE
Need to build an Rpi4 Lineageos image with custom launcher

### ISSUE THREAD

**Issue by ramasamyesvar** [lineage-rpi/android_kernel_brcm_rpi#3]
Hi,
      I want to build an android image that will run a custom launcher and a restricted set of app for students (who can't afford laptop) which will run on rpi4. I found you mention you did not share all device-specific files to build images other than kernel. 
      I want to understand what modules make Lineageos not suitable for commercial and remove them if possible.  I would also appreciate if you could provide device file to build a light version my self. Or please suggest an alternative android which runs on rpi4
Thanks

**Comment by KonstaT** [comment]
Closing this as launchers have nothing to do with kernels. You don't need to build anything to install applications either.

You can't use images I've publicly provided for commercial use. You can consider that something you've agreed to when using those builds.

There's source code and build instructions for my LineageOS 14.1 & 15.1 builds for the Pi 3. There's also android-rpi project.
