### ISSUE TITLE
Waveshare xinch DSI touchscreen support

### ISSUE THREAD

**Issue by belliash** [lineage-rpi/android_kernel_brcm_rpi#32]
### Describe the bug

Is it possible to add support for Waveshare DSI touchscreen? I got this specific one: https://www.waveshare.com/wiki/7inch_DSI_LCD_(C) which requires additional work. Unfortunately, vendor publishes only binaries for some specific Linux kernel.

On the other hand, there is an open pull request: https://github.com/raspberrypi/linux/pull/5433 which enables support for most (all?) touchscreens from Waveshare. Could you include the patch from above pull request into the LineageOS build, please?

### Steps to reproduce the behaviour

https://github.com/raspberrypi/linux/pull/5433 - please include this, as there are many touchscreens available and supporting them would be a step forward to many RPi users.

### Device (s)

Raspberry Pi 4 Mod. B

### System

Lineage 20

**Comment by KonstaT** [comment]
It will be supported on my builds as well if/when this lands on the upstream Raspberry Pi kernel.

Looks like this is on Linux 6.1 for now and I'm not sure if it will be backported to 5.15 (or can be with reasonable effort). So likely looking at Android 14 that I'll ship with 6.1 kernel or Android 13 with separate 6.1 kernel add-on that I already have posted for the AOSP builds (you can also use it with LineageOS 20).

**Comment by belliash** [comment]
I doubt it will be backported. Would be nice if you could update AOSP kernel as well as publish 6.1 based kernel for LineageOS after mentioned PR gets merged.

**Comment by belliash** [comment]
https://github.com/raspberrypi/linux/pull/5433 got merged.

**Comment by KonstaT** [comment]
Please test the attached Linux 6.1 kernel add-on (TWRP flashable zip) and report back. You can test this with AOSP 13 or LineageOS 20 builds. In addition to flashing the kernel you would need to add 'dtoverlay=vc4-kms-dsi-waveshare-panel,...' for the specific panel to /boot/config.txt and remove /boot/resolution.txt.

[AOSP13-20230426-KonstaKANG-rpi4-6.1-kernel.zip](https://github.com/lineage-rpi/android_kernel_brcm_rpi/files/11336468/AOSP13-20230426-KonstaKANG-rpi4-6.1-kernel.zip)

**Comment by belliash** [comment]
I have finally managed to give it a try and I think there is something wrong.
I power rpi on, the red and green leds on rpi are solid and green led on lcd is blinking. LineageOS 20 starts booting, green led on rpi turns of and starts blinking, green led on lcd stops blinking (this is a good sign), but after a while, red led on rpi goes out for a while and this repeats all the time.

LCD is black, so I don't see any progress or errors but as red (power) led on rpi goes out for around 1sec, I think it is stuck in some boot loop.

**Comment by KonstaT** [comment]
Did you install the above zip in TWRP and modify /boot/config.txt and remove /boot/resolution.txt as suggested?

Impossible to say just by the blinking LEDs without seeing any logs (logcat, dmesg). You can crab logs using serial console adapter or ADB on the USB-C port (you need to have powered USB-C hub or 5V on the GPIO and USB debugging needs to be enabled beforehand from the developer options).

**Comment by belliash** [comment]
I have modified config.txt and removed resolution.txt. However, I have flashed IMG file (lineage-20.0-20230321-UNOFFICIAL-KonstaKANG-rpi4.zip) with RPi Imager 1.7.4 and I have overwritten all files in /boot partition from attached kernel zip file. I cannot use TWRP as it does not support my LCD display. I cannot do anything with a blank screen.

I will try to attach serial console with UART controller and provide some logs. ADB won't work for me as well, as I don't have touchscreen working, what means I cannot do anything in the UI (i.e. enable debugging in developer options).

**Comment by KonstaT** [comment]
You can of course use HDMI display to boot to Android/TWRP first.

Using the DSI display after that would only require adding the one line to /boot/config.txt and removing/adjusting /boot/resolution.txt.

**Comment by belliash** [comment]
One more question - is it possible to boot it from USB or it needs to be flashed on SD card?

**Comment by KonstaT** [comment]
> One more question - is it possible to boot it from USB or it needs to be flashed on SD card?

You need to adjust /boot/config.txt to boot from USB. Please read the relevant FAQ section.

**Comment by belliash** [comment]
OK, that was my fault. I have flashed it on USB pendrive and I have forgotten to uncomment the `dtoverlay=android-usb` what probably lead to kernel panic (unable to mount rootfs).

Everything seems working properly now, except brightness control. I have successfully rotated screen for 180 degree, but I cannot dim it or turn it off after some specified timeout. Also splash and UI displays upside-down for me and rotates just after system is booted up. In Linux this could be fixed with video= parameter but here this takes no effects. This is minor, but would be nice if it would be possible to control its brightness.

**Comment by KonstaT** [comment]
Have you tested uncommenting `dtoverlay=rpi-backlight` in /boot/config.txt? That's what the official Raspberry 7" DSI touchscreen uses as backlight driver but IDK if these Waveshare ones work with the same driver. There's nothing in the Waveshare specifc KMS overlay related to backlight at least.

**Comment by belliash** [comment]
It uses Goodix driver which exposes some interface through /proc to control backlight. From what I can see `dtoverlay=rpi-backlight` is uncommented by default, so it does not work.

**Comment by KonstaT** [comment]
Goodix driver is for the touchscreen part. It doesn't have anything for backlight control.

In any case, my Android lights HAL only supports `/sys/class/backlight/rpi_backlight/brightness` to control the display brightness using the brightness slider in Android UI. Otherwise you would need to echo the brightness value manually.

`dtoverlay=rpi-backlight` is commented out by default.

Thank you for testing and reporting back. Closing as this is now working to this level at least.
