### ISSUE TITLE
Microphone does not work with rpi4

### ISSUE THREAD

**Issue by ramasamyesvar** [lineage-rpi/android_kernel_brcm_rpi#4]
Hi ,
  I tried this rpi4 image and found everything works except for microphone.  In both 3.5 audio jack and with Bluetooth. 

 The recorder app crashed is I tried to record audio. Skype call does not have voice. 
While the same works with rpi3. This is after running rpi4-audio.sh.
Am I missing something

**Comment by KonstaT** [comment]
Only USB microphones work for now. Skype/WhatsApp/etc calls are reported working.

3.5 mm jack doesn't have audio input so that's never going to work of course. Bluetooth microphone is something that needs looking into.
